export const GENERAL_REF_RANGES: Record<string, string> = {
    "Hemoglobina": "Ref: ~13.5-17.5 g/dL (H), ~12.0-15.5 g/dL (M)",
    "Hematocrito": "Ref: ~40-52% (H), ~36-48% (M)",
    "VCM": "Ref: ~80-100 fL",
    "HCM": "Ref: ~27-33 pg",
    "CHCM": "Ref: ~32-36 g/dL",
    "ADE/RDW": "Ref: ~11.5-15%",
    "Leucocitos": "Ref: ~4.0-11.0 x 10^9/L",
    "Neutrofilos (%)": "Ref: ~40-75%",
    "Linfocitos (%)": "Ref: ~20-45%",
    "Monocitos (%)": "Ref: ~2-12%",
    "Eosinofilos (%)": "Ref: ~0-6%",
    "Basofilos (%)": "Ref: ~0-2%",
    "Neutrofilos (Absoluto)": "Ref: ~1.5-7.5 x 10^9/L",
    "Linfocitos (Absoluto)": "Ref: ~1.0-4.0 x 10^9/L",
    "Monocitos (Absoluto)": "Ref: ~0.2-1.0 x 10^9/L",
    "Eosinofilos (Absoluto)": "Ref: ~0.0-0.5 x 10^9/L",
    "Basofilos (Absoluto)": "Ref: ~0.0-0.2 x 10^9/L",
    "Plaquetas": "Ref: ~150-450 x 10^9/L",
    "Glucosa": "Ref: ~70-100 mg/dL (Ayunas)",
    "Urea": "Ref: ~15-45 mg/dL",
    "Creatinina": "Ref: ~0.7-1.3 mg/dL (H), ~0.6-1.1 mg/dL (M)",
    "Sodio": "Ref: ~136-145 mEq/L",
    "Potasio": "Ref: ~3.5-5.1 mEq/L",
    "Cloro": "Ref: ~98-107 mEq/L",
    "Calcio": "Ref: ~8.5-10.5 mg/dL (Total)",
    "Fosforo": "Ref: ~2.5-4.5 mg/dL",
    "Magnesio": "Ref: ~1.7-2.3 mg/dL",
    "Bilirrubina Total": "Ref: ~0.2-1.2 mg/dL",
    "GOT/AST": "Ref: < 40 U/L",
    "GPT/ALT": "Ref: < 40 U/L",
    "GGT": "Ref: < 60 U/L (H), < 40 U/L (M) (Varía)",
    "Fosfatasa Alcalina": "Ref: ~40-130 U/L (Adultos)",
    "LDH": "Ref: ~140-280 U/L (Varía mucho)",
    "Proteinas Totales": "Ref: ~6.0-8.3 g/dL",
    "Albumina": "Ref: ~3.5-5.2 g/dL",
    "Acido Urico": "Ref: ~3.5-7.2 mg/dL (H), ~2.5-6.0 mg/dL (M)",
    "Hierro": "Ref: ~60-170 µg/dL (H), ~50-160 µg/dL (M)",
    "Proteina C Reactiva": "Ref: < 5-10 mg/L",
    "TSH": "Ref: ~0.4-4.5 mIU/L",
    "T4 Libre": "Ref: ~0.8-1.8 ng/dL",
    "Vitamina D 25-Hidroxi": "Ref: Suficiencia >20-30 ng/mL",
    "Amilasa": "Ref: ~25-125 U/L",
    "Lipasa": "Ref: ~10-70 U/L",
    "Tiempo Protrombina (TP)": "Ref: ~10-13 segundos",
    "INR": "Ref: ~0.8-1.2 (No anticoagulado)",
    "TTPA": "Ref: ~25-35 segundos",
    "Fibrinogeno Derivado": "Ref: ~200-400 mg/dL",
    "Colesterol": "Ref: Deseable <200 mg/dL",
    "Trigliceridos": "Ref: Deseable <150 mg/dL",
    "Creatinkinasa (CK)": "Ref: ~40-320 U/L (Varía)",
    "Hematies": "Ref: ~4.4-5.9 x 10^12/L",
    "HDL-Colesterol": "Ref: >40 mg/dL (H), >50 mg/dL (M)",
    "LDL-Colesterol": "Ref: <155 mg/dL",
    "VLDL-Colesterol": "Ref: 10-32 mg/dL",
    "Filtrado Glomerular": "Ref: >60 mL/min",
    "Ancho Dist. Plaquetaria": "Ref: 15-65%",
    "Cociente N/L": "Ref: ~1-3"
};

export const PREDEFINED_DESCRIPTIONS: Record<string, string> = {
    "Hemoglobina": "La hemoglobina es una proteína en los glóbulos rojos que transporta oxígeno. Niveles bajos (anemia) causan fatiga; niveles altos pueden indicar deshidratación o policitemia.",
    "Hematocrito": "Mide el porcentaje de glóbulos rojos en la sangre. Importante para diagnosticar anemia (bajo) o policitemia (alto).",
    "VCM": "El Volumen Corpuscular Medio indica el tamaño promedio de los glóbulos rojos. Ayuda a clasificar anemias (microcítica, normocítica, macrocítica).",
    "HCM": "La Hemoglobina Corpuscular Media es la cantidad promedio de hemoglobina por glóbulo rojo. Valores bajos se ven en anemias por deficiencia de hierro.",
    "CHCM": "La Concentración de Hemoglobina Corpuscular Media mide la concentración de hemoglobina dentro de un volumen dado de glóbulos rojos. Baja en deficiencia de hierro, alta en esferocitosis.",
    "ADE/RDW": "La Amplitud de Distribución Eritrocitaria mide la variación en el tamaño de los glóbulos rojos. Elevada (anisocitosis) sugiere deficiencia de hierro o vitamina B12/folato.",
    "Leucocitos": "Los glóbulos blancos combaten infecciones. Altos (leucocitosis) pueden indicar infección/inflamación; bajos (leucopenia) aumentan riesgo de infección.",
    "Neutrofilos (%)": "Tipo de leucocito principal contra infecciones bacterianas. Aumentan en infecciones bacterianas agudas.",
    "Linfocitos (%)": "Tipo de leucocito clave en inmunidad viral y crónica. Aumentan en infecciones virales, algunos cánceres; disminuyen en inmunodeficiencias.",
    "Monocitos (%)": "Tipo de leucocito que combate infecciones crónicas y participa en la limpieza celular. Aumentan en infecciones crónicas, enfermedades autoinmunes.",
    "Eosinofilos (%)": "Tipo de leucocito implicado en alergias y defensa contra parásitos. Aumentan en reacciones alérgicas, asma, infecciones parasitarias.",
    "Basofilos (%)": "Tipo de leucocito que libera histamina en reacciones alérgicas. Aumentan en algunas alergias y trastornos mieloproliferativos.",
    "Neutrofilos (Absoluto)": "Recuento absoluto de neutrófilos, más preciso que el porcentaje para evaluar riesgo de infección (neutropenia).",
    "Linfocitos (Absoluto)": "Recuento absoluto de linfocitos. Útil para evaluar estado inmunitario.",
    "Monocitos (Absoluto)": "Recuento absoluto de monocitos.",
    "Eosinofilos (Absoluto)": "Recuento absoluto de eosinófilos. Aumenta en alergias y parasitosis.",
    "Basofilos (Absoluto)": "Recuento absoluto de basófilos.",
    "Plaquetas": "Fragmentos celulares para la coagulación. Bajas (trombocitopenia) causan sangrado; altas (trombocitosis) riesgo de coágulos.",
    "Glucosa": "Azúcar principal en sangre, fuente de energía. Clave para diabetes. Alta (hiperglucemia) o baja (hipoglucemia) tienen implicaciones serias.",
    "Urea": "Producto de desecho del metabolismo proteico, eliminado por riñones. Indicador de función renal e hidratación.",
    "Creatinina": "Producto de desecho muscular filtrado por riñones. Indicador clave de la función renal.",
    "Sodio": "Electrolito esencial para equilibrio hídrico y función nerviosa/muscular. Alteraciones (hiper/hiponatremia) son importantes.",
    "Potasio": "Electrolito vital para función cardíaca, nerviosa y muscular. Niveles anormales (hiper/hipopotasemia) pueden ser peligrosos.",
    "Cloro": "Electrolito que ayuda a mantener el equilibrio de líquidos y ácido-base. Sus niveles suelen cambiar junto con el sodio.",
    "Calcio": "Mineral esencial para huesos, dientes, función muscular y nerviosa, y coagulación. Regulado por hormonas.",
    "Fosforo": "Mineral importante para huesos, energía celular y función renal. Regulado junto con el calcio.",
    "Magnesio": "Mineral implicado en numerosas reacciones enzimáticas, función muscular y nerviosa. Su deficiencia puede causar calambres o arritmias.",
    "Bilirrubina Total": "Producto de la degradación de la hemoglobina, procesado por el hígado. Niveles altos causan ictericia y pueden indicar problemas hepáticos o hemólisis.",
    "GOT/AST": "Enzima del hígado, corazón y músculos. Elevada indica daño en estos tejidos (ej. hepatitis, infarto).",
    "GPT/ALT": "Enzima principalmente hepática. Más específica para daño hepático que AST. Elevada en hepatitis.",
    "GGT": "La Gammaglutamil Transferasa es una enzima hepática sensible al daño hepático, especialmente por alcohol u obstrucción biliar.",
    "Fosfatasa Alcalina": "Enzima del hígado, huesos, riñón. Elevada en enfermedades hepáticas (colestasis) u óseas (Paget, crecimiento).",
    "LDH": "La Lactato Deshidrogenasa es una enzima presente en muchos tejidos. Elevada indica daño tisular general, poco específica.",
    "Proteinas Totales": "Suma de todas las proteínas en sangre, principalmente albúmina y globulinas. Refleja estado nutricional y función hepática/renal.",
    "Albumina": "Proteína más abundante en plasma, producida por el hígado. Mantiene presión oncótica y transporta sustancias. Baja en enfermedad hepática/renal, malnutrición.",
    "Acido Urico": "Producto del metabolismo de las purinas. Niveles altos pueden causar gota o cálculos renales.",
    "Hierro": "El hierro es un mineral esencial para la producción de hemoglobina y el transporte de oxígeno. Niveles bajos causan anemia ferropénica (fatiga, palidez). Niveles altos (hemocromatosis) pueden dañar órganos como el hígado y el corazón.",
    "Proteina C Reactiva": "Marcador de inflamación aguda. Producida por el hígado en respuesta a infección o daño tisular.",
    "TSH": "La Hormona Estimulante del Tiroides regula la producción de hormonas tiroideas. Clave para diagnosticar hipo/hipertiroidismo.",
    "T4 Libre": "Tiroxina libre, principal hormona tiroidea activa. Mide directamente la función tiroidea.",
    "Vitamina D 25-Hidroxi": "Mide los niveles de Vitamina D. Esencial para la salud ósea y la absorción de calcio. Deficiencia común.",
    "Amilasa": "Enzima producida por páncreas y glándulas salivales, digiere carbohidratos. Elevada en pancreatitis.",
    "Lipasa": "Enzima producida por el páncreas, digiere grasas. Más específica que la amilasa para pancreatitis.",
    "Tiempo Protrombina (TP)": "Mide el tiempo que tarda en formarse un coágulo (vía extrínseca). Se usa para controlar anticoagulantes orales (Sintrom).",
    "INR": "Ratio Normalizado Internacional, estandariza el TP. Usado para monitorizar terapia con antagonistas de Vitamina K.",
    "TTPA": "Tiempo de Tromboplastina Parcial Activada. Mide la vía intrínseca de la coagulación. Usado para monitorizar heparina.",
    "Fibrinogeno Derivado": "Proteína esencial para la formación de coágulos. Niveles bajos aumentan riesgo de sangrado; altos pueden ser reactantes de fase aguda.",
    "Colesterol": "El colesterol es una sustancia grasa necesaria para las células, pero su exceso en sangre (hipercolesterolemia) es un factor de riesgo cardiovascular importante, ya que puede depositarse en las arterias.",
    "Trigliceridos": "Son otro tipo de grasa en la sangre. Niveles elevados, a menudo junto con colesterol alto, aumentan el riesgo de enfermedades del corazón y pueden estar relacionados con la dieta, el sobrepeso o la diabetes.",
    "Creatinkinasa (CK)": "La CK es una enzima que se encuentra en el corazón, el cerebro y, sobre todo, en los músculos. Niveles elevados en sangre suelen indicar daño o estrés muscular, como el que puede ocurrir por ejercicio intenso, lesiones o ciertas enfermedades musculares.",
    "Hematies": "Recuento de glóbulos rojos en sangre. Valores bajos sugieren anemia; altos, policitemia.",
    "HDL-Colesterol": "El HDL es el 'colesterol bueno'; niveles altos se asocian con menor riesgo cardiovascular.",
    "LDL-Colesterol": "El LDL es el 'colesterol malo'; niveles elevados favorecen la aterosclerosis y la enfermedad cardiaca.",
    "VLDL-Colesterol": "Las VLDL transportan triglicéridos; valores altos indican dislipidemia y mayor riesgo cardiovascular.",
    "Filtrado Glomerular": "Estimación de la función renal; valores bajos reflejan deterioro del filtrado de los riñones.",
    "Ancho Dist. Plaquetaria": "Indica la variabilidad del tamaño de las plaquetas, útil para valorar trastornos de la médula u otros procesos.",
    "Cociente N/L": "Relación neutrófilos/linfocitos usada como marcador de inflamación sistémica o estrés."
};
